"""Added tracking_number column

Revision ID: 373734113000
Revises: 
Create Date: 2025-02-17 11:43:42.990032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373734113000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_details', schema=None) as batch_op:
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
