"""Create favourites table

Revision ID: 52732b1789a8
Revises: 7de6599be9b1
Create Date: 2025-02-03 09:22:04.807363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52732b1789a8'
down_revision = '7de6599be9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('mailing_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_type')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_code', sa.String(length=50), nullable=False),
    sa.Column('voucher_description', sa.String(length=1000), nullable=False),
    sa.Column('voucherType_id', sa.Integer(), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('eligible_categories', sa.JSON(), nullable=True),
    sa.Column('expiry_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['voucherType_id'], ['voucher_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_code')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_vouchers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.BOOLEAN(), nullable=True))

    op.drop_table('user_vouchers')
    op.drop_table('favorites')
    op.drop_table('vouchers')
    op.drop_table('voucher_types')
    op.drop_table('mailing_posts')
    op.drop_table('mailing_list')
    # ### end Alembic commands ###
