"""Add status column to trade_details

Revision ID: 99023f97fea1
Revises: 
Create Date: 2025-01-20 02:10:57.829111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99023f97fea1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_details', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status', sa.String(length=50), nullable=False, server_default='Pending')
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('trade_details', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
