"""added shipping stuff

Revision ID: bd9a3c04de8a
Revises: 99023f97fea1
Create Date: 2025-02-03 04:53:44.160416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9a3c04de8a'
down_revision = '99023f97fea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_option', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('street_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('house_block', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_expiry', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('card_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_details', schema=None) as batch_op:
        batch_op.drop_column('card_name')
        batch_op.drop_column('card_expiry')
        batch_op.drop_column('card_number')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('house_block')
        batch_op.drop_column('street_address')
        batch_op.drop_column('shipping_option')

    # ### end Alembic commands ###
